apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API_gbiz
  tags: ['apisix']
  description: |
    APISIXにある、経済産業省gbiz API
  links:
    - title: Management
      url: https://mgmt.api.spklab-isd.com
    - title: Documentation
      url: https://backstage.spklab-isd.com/docs/default/Component/apisix
spec:
  type: openapi
  owner: group:default/team-devops
  lifecycle: experimental
  system: isd-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
    title: Ministry of Economy, Trade and Industry API
    servers:
      - url: https://api.spklab-isd.com/gbiz
    paths:
      /gbiz:
       get:
         operationId: 20231205_経済産業省gBizINFOGET
         requestBody: {}
         responses:
           default:
             description: ''
         security:
           - basicAuth:
               - ' '
         x-apisix-enable_websocket: false
         x-apisix-id: '490400693606155661'
         x-apisix-plugins:
           consumer-restriction:
             _meta:
               disable: false
             whitelist:
               - aiba
           ip-restriction:
             _meta:
               disable: false
             blacklist:
               - 39.110.203.194
               - 122.220.66.182
           proxy-rewrite:
             headers:
               X-hojinInfo-api-token: skDuVidg053dTjOfrgOWEAC5Ty5BvF6x
             uri: /hojin/v1/hojin
         x-apisix-priority: 0
         x-apisix-status: 1
         x-apisix-upstream:
           nodes:
             - host: info.gbiz.go.jp
               port: 443
               weight: 1
           timeout:
             connect: 6
             send: 6
             read: 6
           type: roundrobin
           scheme: https
           pass_host: pass
           keepalive_pool:
             idle_timeout: 60
             requests: 1000
             size: 320

