apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: API_gbiz
  description: |
    APISIXにある、経済産業省gbiz API
  links:
    - title: Management
      url: https://mgmt.api.spklab-isd.com
    - title: Documentation
      url: https://backstage.spklab-isd.com/docs/default/Component/apisix
spec:
  type: API
  owner: Team DevOps
  lifecycle: experimental
  system: isd-system
