apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: API_gbiz
  tags: ['apisix']
  description: |
    APISIXにある、経済産業省gbiz API
  links:
    - title: Management
      url: https://mgmt.api.spklab-isd.com
    - title: Documentation
      url: https://backstage.spklab-isd.com/docs/default/Component/apisix
spec:
  type: openapi
  owner: group:default/team-devops
  lifecycle: experimental
  system: isd-system
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
    title: Ministry of Economy, Trade and Industry API
    servers:
      - url: https://api.spklab-isd.com/gbiz
    paths:
      /gbiz:
      get:
        summary: Get a user
        parameters:
          - in: path
            name: corporate_num
            required: true
            description: 法人番号
            schema:
              type: integer
          - in: path
            name: page_num
            required: true
            description: 1ページの表示数
            schema:
              type: integer
          - in: path
            name: limit
            required: true
            description: APIでのLimit数
            schema:
              type: integer
        responses:
          200:
            description: Success
